// packages/svelte/src/LuminaLoader.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import type { LoaderOptions } from '../../core/LuminaLoader';
  import { createLoader } from '../../api';

  export let show: boolean = true;
  export let container: HTMLElement | string | null = null;
  export let overlay: boolean = false;
  export let type: string = 'spinner';
  export let size: number | string = 32;
  export let color: string | undefined = undefined;
  export let speed: number | undefined = undefined;
  export let theme: string | undefined = undefined;
  export let progress: number | undefined = undefined;
  export let progressVariant: string | undefined = undefined;

  let host: HTMLElement | null = null;
  let loader: ReturnType<typeof createLoader> | null = null;

  function mountLoader() {
    if (loader) return;

    let targetEl: HTMLElement | null = null;
    if (container) {
      if (typeof container === 'string') {
        const q = document.querySelector(container);
        targetEl = q instanceof HTMLElement ? q : null;
      } else {
        targetEl = container as HTMLElement;
      }
    } else {
      targetEl = host;
    }

    const finalTarget: HTMLElement | string =
      overlay && !container ? document.body : (targetEl ?? document.body);

    loader = createLoader({
      type,
      size,
      color,
      speed,
      theme,
      progress,
      progressVariant,
      target: finalTarget as any,
    } as LoaderOptions);

    if (show) {
      loader.show();
    }
  }

  function destroyLoader() {
    if (!loader) return;
    loader.destroy();
    loader = null;
  }

  $: if (loader) {
    if (show) loader.show(); else loader.hide();
  }

  $: if (loader && (type || size || color || speed || theme || progress || progressVariant)) {
    // Recreate loader on option changes to pick up changes
    destroyLoader();
    mountLoader();
  }

  onMount(() => {
    mountLoader();
  });

  onDestroy(() => {
    destroyLoader();
  });
</script>

{#if !overlay}
  <div bind:this={host} class="lumina-loader-host"></div>
{/if}

<style>
  .lumina-loader-host {
    display: contents;
  }
</style>

// src/adapters/vue/LuminaLoader.vue
<template>
  <div v-if="!overlay" ref="host" class="lumina-loader-host"></div>
</template>

<script setup lang="ts">
import { onMounted, onBeforeUnmount, watch, toRef, ref, computed } from 'vue';
import { createLoader } from '../../api';
import type { LoaderOptions } from '../../core/LuminaLoader';

interface Props extends Omit<LoaderOptions, 'target'> {
  show?: boolean;
  container?: HTMLElement | string;
}

const props = withDefaults(defineProps<Props>(), {
  show: true,
});

const emit = defineEmits<{
  show: [];
  hide: [];
}>();

let loader: ReturnType<typeof createLoader> | null = null;
const host = ref<HTMLElement | null>(null);
const showHost = computed(() => !props.overlay);

function mountLoader() {
  if (loader) return;

  const hostIsConnected = !!(
    host.value && (host.value as HTMLElement).isConnected
  );

  const targetEl =
    props.container ?? (hostIsConnected ? host.value : document.body);

  const finalTarget =
    props.overlay && !props.container ? document.body : targetEl;

  loader = createLoader({
    ...(props as LoaderOptions),
    target: finalTarget,
  });

  if (props.show) {
    loader.show();
    emit('show');
  }
}

function destroyLoader() {
  if (!loader) return;
  loader.destroy();
  loader = null;
}

onMounted(() => {
  mountLoader();
});

onBeforeUnmount(() => {
  destroyLoader();
});

// Watch show prop changes
watch(
  () => props.show,
  (newValue) => {
    if (!loader) {
      mountLoader();
      return;
    }

    if (newValue) {
      loader.show();
      emit('show');
    } else {
      loader.hide();
      emit('hide');
    }
  },
);

// Watch for other prop changes - recreate loader if needed
watch(
  () => ({
    type: props.type,
    size: props.size,
    color: props.color,
    speed: props.speed,
    overlay: props.overlay,
    theme: props.theme,
    progress: props.progress,
    progressVariant: props.progressVariant,
  }),
  () => {
    destroyLoader();
    mountLoader();
  },
  { deep: true },
);
</script>

<style scoped>
.lumina-loader-host {
  display: contents;
}
</style>
